[package]
name = "oxy"
version = "4.0.0-dev"
authors = ["Jenna Magius <pyrosim@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_cbor = "0.9.0"
toml = "0.4.8"
